# Generated by Django 2.2.4 on 2021-06-24 10:29


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inputargs',
            fields=[
                ('id_args', models.IntegerField(primary_key=True, serialize=False)),
                ('args', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
